### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by GuGuMur** [AbCooly/nonebot_plugin_wolf_kill#3]
* 简述：自定义开盘后无法给全部参与成员发送私信
```
10-17 10:29:11 [ERROR] nonebot | Running matcher <Matcher from src.plugins.wolf-kill, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/home/Bot/WaterBot/venv/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/Bot/WaterBot/venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/Bot/WaterBot/qb/./src/plugins/wolf-kill/__init__.py", line 214, in restart_game
    await game_main(bot, group)
  File "/home/Bot/WaterBot/qb/./src/plugins/wolf-kill/__init__.py", line 378, in game_main
    res = get_role_info(d[qq])
KeyError: '114514'
```

**Comment by AbCooly** [comment]
KeyError: '114514' 这报错怎么这么臭

**Comment by kaluo686** [comment]
> KeyError: '114514' 这报错怎么这么臭

笑死了哈哈哈哈114514
