### ISSUE TITLE
[报错]无法正常运行插件

### ISSUE THREAD

**Issue by kaluo686** [AbCooly/nonebot_plugin_wolf_kill#6]
![捕获](https://user-images.githubusercontent.com/118961487/203731684-d150274e-4eb9-445f-987c-7835dbab763b.PNG)
安装完成过后在库中只有该文件
以下是运行时的终端代码
```code``` E:\nbot\nb1>  & 'E:\python3.8.10\python.exe' 'c:\Users\Han\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '3004' '--' 'e:\nbot\nb1\bot.py'  
[SUCCESS] nonebot | NoneBot is initializing...
[INFO] nonebot | Current Env: prod
[SUCCESS] nonebot | Succeeded to import "echo"
**[ERROR] nonebot | Failed to import "nonebot-plugin-wolf-kill"**
Traceback (most recent call last):
  File "e:\nbot\nb1\bot.py", line 24, in <module>
    nonebot.load_plugin('nonebot-plugin-wolf-kill')
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
 File "E:\python3.8.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "E:\python3.8.10\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot-plugin-wolf-kill'
Traceback (most recent call last):
  File "e:\nbot\nb1\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\load.py", line 57, in load_all_plugins
    manager = PluginManager(module_path, plugin_dir)
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\manager.py", line 52, in __init__
    self.prepare_plugins()
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\manager.py", line 94, in prepare_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: nonebot-plugin-wolf-kill! Check your plugin name
PS E:\nbot\nb1>  e:; cd 'e:\nbot\nb1'; & 'E:\python3.8.10\python.exe' 'c:\Users\Han\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '3052' '--' 
'e:\nbot\nb1\bot.py'
 [SUCCESS] nonebot | NoneBot is initializing...
 [INFO] nonebot | Current Env: prod
 [SUCCESS] nonebot | Succeeded to import "echo"
**[ERROR] nonebot | Failed to import "nonebot-plugin-wolf-kill"**
Traceback (most recent call last):
  File "e:\nbot\nb1\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml     
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins    
    return manager.load_all_plugins()
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>       
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "E:\python3.8.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin     
    module = importlib.import_module(name)
  File "E:\python3.8.10\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'nonebot-plugin-wolf-kill'**
11-24 16:25:24 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_remake"
11-24 16:25:24 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
 [SUCCESS] nonebot | Running NoneBot...
 [INFO] uvicorn | Started server process [19092]
 [INFO] uvicorn | Waiting for application startup.
[INFO] uvicorn | Application startup complete.
 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:26437 (Press CTRL+C to quit)` 

我发现了有以下两个报错
```code```ModuleNotFoundError: No module named 'nonebot-plugin-wolf-kill'
和
```code```[ERROR] nonebot | Failed to import "nonebot-plugin-wolf-kill"
两处报错
请问该如何解决

**Comment by kaluo686** [comment]
我个人认为是缺少了文件，因为我安装了1.02版本就可以正常运行并且有两个文件，但是2.00就不可以，我还没有找到原因，请帮帮我

**Comment by AbCooly** [comment]
你把旧版本删了换新版本试试 新版本我上传到release了

**Comment by kaluo686** [comment]
> 你把旧版本删了换新版本试试 新版本我上传到release了

非常感谢，我用安装指令安装一次过后，把压缩包里的文件改个名字放进库里，最后删掉
`nonebot.load_from_toml("pyproject.toml")`

再手动加一条

`nonebot.load_plugin('nonebot_plugin_wolf_kill')`

就解决了
非常感谢作者！！
